### ISSUE TITLE
FBI Reloaded was broken and broke the original FBI

### ISSUE THREAD

**Issue by thevideogameraptorboggle** [TheRealZora/FBI-Reloaded#9]
I hit the maximum of 300 pieces of software, but I found an application called 3DSBank that will allow me to store more on my SD card, by making more banks of 300 pieces of software. It lacked all the default applications, but I was able to install them via FBI and the backup homebrew menu. I installed FBI Reloaded onto my second bank, because I heard it’s better, but it refused to install anything I threw at it. And after installing Reloaded, my original FBI also refused to install anything. Even the FBI CIA on my default bank refused to install anything. I deleted Reloaded and the original FBI was still broken for a time, but I tried the download links that were broken before again and they now worked all of a sudden? I'm still convinced that FBI Reloaded broke them, I could install it fine via regular FBI, and could install nothing else after installing Reloaded.

I got error code 0xD963FA84, and the description was a "SSL Connect Error (644)"

**Comment by thevideogameraptorboggle** [comment]
Nevermind, after rebooting itself, FBI broke again, same error as before.

**Comment by ZeroSkill1** [comment]
You mention:
> refused to install anything I threw at it

which, if I'm understanding correctly, means installations fail with:
> 0xD963FA84, and the description was a "SSL Connect Error (644)"

This is not related to FBI or FBI Reloaded. FBI Reloaded cannot "break" anything. There is little to no difference between FBI and FBI Reloaded, and the changes made in Reloaded are pretty minor and cannot break things.

The error you are seeing, assuming it is the *only* error you see every time you try Remote Install, is a network-related error. SSL errors in particular can occur when you try downloading via HTTPS while your system time/date are incorrect.

**Comment by thevideogameraptorboggle** [comment]
I was about to ask if my 3DS got screwed over by daylight savings time, but I updated it and that doesn't appear to be the case, still broken.

Is there a way to just, completely delete and re-install FBI?

**Comment by thevideogameraptorboggle** [comment]
I also did a SD card health check, it didn't seem to find any significant errors.

**Comment by ZeroSkill1** [comment]
What website are you trying to download from? Many sites are now using newer versions of TLS that are not supported on the 3DS, which can cause those SSL errors.

**Comment by thevideogameraptorboggle** [comment]
I'm downloading them via the 3DSQRCodes subreddit, and most of those links
are via Catbox.

I'm using an original model, non XL, non "New" 3DS, if that matters.

**Comment by ZeroSkill1** [comment]
catbox URLs currently work in FBI. It is likely that the links you tried to use are dead. Another possibility is your internet service provider doing something shady that prevents a proper connection to the server.

This is not something we can fix.

Try different websites that are specifically made to work on the 3DS.
